EMAIL_REGEX = r'[1]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$'


ERROR_STATUS_CODES = {
    "VALIDATION_ERROR_STATUS_CODE": 403,
    "API_FAILED_STATUS_CODE": 400
}

SUCCESS_STATUS_CODES= {
    "API_SUCCESS_STATUS_CODE": 200
}